version: "3.0"
services:
  lvtn_nginx:
    image: nginx
    container_name: lvtn-nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 9980
        protocol: tcp
    volumes:
      - "./tests/stubdata:/etc/nginx/html:ro"
      - "./tests/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: lvtn-ftpd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - target: 21
        published: 9921
        protocol: tcp
        mode: host
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
    volumes:
      # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./tests/stubdata:/home/test/"
      #- "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
      # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
      - "./tests/ssl:/etc/ssl/private/"
      # or ssl/tls with Let's Encrypt (cert and key as two files)
      #      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
      #      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "ftpd_server"
      FTP_USER_NAME: test
      FTP_USER_PASS: test
      #ADDED_FLAGS: "--verboselog"
